#!/usr/bin/env node
/**
 * MirageInk (TimeWrite / 智写时光) 项目完整性自动检测脚本
 * 检查 TypeScript 类型、Rust 编译、必需文件、关键导入一致性、迁移防回归
 *
 * 运行: pnpm check
 *       pnpm check --fast   # 快速模式：跳过 cargo check（约 10s 内完成）
 */

import { existsSync, readFileSync, mkdirSync, writeFileSync, readdirSync } from 'fs'
import { join, dirname } from 'path'
import { execSync } from 'child_process'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const ROOT = join(dirname(__filename), '..')

// 快速模式：跳过 Rust 编译检查（适合前端日常改动后的快速回归）
const FAST = process.argv.includes('--fast')

/**
 * tauri-build 会校验 tauri.conf.json 中 frontendDist（"../dist"）路径必须存在，
 * 否则 cargo check 直接报错。若 dist/ 缺失（如刚执行过 pnpm clean），
 * 先写入占位 index.html（后续 vite build 会清空覆盖，且 dist/ 已被 .gitignore 忽略）。
 */
function ensureFrontendDist() {
  const distDir = join(ROOT, 'dist')
  if (existsSync(distDir)) return
  try {
    mkdirSync(distDir, { recursive: true })
    writeFileSync(
      join(distDir, 'index.html'),
      '<!doctype html><html><head><meta charset="utf-8"><title>placeholder</title></head><body><!-- auto-generated by scripts/check.mjs for tauri-build frontendDist check --></body></html>\n',
    )
    console.log('  ⏭️  dist/ 不存在，已写入占位 index.html（供 tauri-build 校验，可随时 pnpm build 覆盖）')
  } catch { /* 创建失败时交给 cargo check 自行报错 */ }
}

let passed = 0
let failed = 0
const errors = []
const warnings = []

function check(desc, condition, isWarning = false) {
  if (condition) {
    console.log(`  ✅  ${desc}`)
    passed++
  } else {
    const icon = isWarning ? '⚠️ ' : '❌'
    console.log(`  ${icon}  ${desc}`)
    if (isWarning) warnings.push(desc)
    else { errors.push(desc); failed++ }
  }
}

function fileExists(relPath) {
  return existsSync(join(ROOT, relPath))
}

function fileContains(relPath, ...patterns) {
  try {
    const content = readFileSync(join(ROOT, relPath), 'utf-8')
    return patterns.every(p => content.includes(p))
  } catch { return false }
}

function cargoAvailable() {
  try {
    execSync('cargo --version', { cwd: ROOT, stdio: 'pipe', timeout: 5000 })
    return true
  } catch { return false }
}

// ============================================================
console.log('\n🔍  MirageInk (TimeWrite) 项目完整性检测\n')
console.log('='.repeat(50))

// ── 0. TypeScript 类型检查 ──────────────────────────────────
console.log('\n🔎  [0/10] TypeScript 类型检查')
try {
  execSync('npx tsc --noEmit', { cwd: ROOT, stdio: 'pipe', timeout: 120000 })
  console.log('  ✅  tsc --noEmit 通过（0 个类型错误）')
  passed++
} catch (e) {
  const stderr = e.stderr?.toString() || e.stdout?.toString() || ''
  const errorLines = stderr.split('\n').filter(l =>
    l.includes('error TS') && !l.includes('npm warn')
  )
  if (errorLines.length > 0) {
    console.log(`  ❌  tsc --noEmit 发现 ${errorLines.length} 个类型错误：`)
    errorLines.slice(0, 15).forEach(l => console.log(`     ${l.trim()}`))
    if (errorLines.length > 15) console.log(`     ... 还有 ${errorLines.length - 15} 个错误`)
    errors.push(`TypeScript 类型错误 (${errorLines.length} 个)`)
    failed++
  } else {
    console.log('  ❌  tsc --noEmit 执行失败')
    errors.push('TypeScript 编译失败（无具体错误信息）')
    failed++
  }
}

// ── 1. Rust 编译检查 ────────────────────────────────────────
console.log('\n🦀  [1/10] Rust 编译检查 (cargo check)')
if (FAST) {
  console.log('  ⏭️  快速模式 (--fast)：跳过 cargo check，仅做文件结构检查')
} else if (!cargoAvailable()) {
  console.log('  ⚠️  未检测到 Rust/Cargo 工具链，跳过 Rust 编译检查')
  warnings.push('Rust 工具链未安装，跳过 cargo check')
} else {
  ensureFrontendDist()
  try {
    execSync('cargo check', { cwd: join(ROOT, 'src-tauri'), stdio: 'pipe', timeout: 300000 })
    console.log('  ✅  cargo check 通过（0 个错误）')
    passed++
  } catch (e) {
    const stderr = e.stderr?.toString() || e.stdout?.toString() || ''
    // 兼容 rustc 的 "error[E0433]..." 与 build script / tauri-build 的 "error: ..." 两种格式
    const errorLines = stderr.split('\n').filter(l =>
      (l.includes('error[') || l.includes('error:')) && !l.includes('warning[') && !l.includes('npm warn')
    )
    if (errorLines.length > 0) {
      console.log(`  ❌  cargo check 发现 ${errorLines.length} 个编译错误：`)
      errorLines.slice(0, 10).forEach(l => console.log(`     ${l.trim()}`))
      if (errorLines.length > 10) console.log(`     ... 还有 ${errorLines.length - 10} 个错误`)
      errors.push(`Rust 编译错误 (${errorLines.length} 个)`)
      failed++
    } else {
      // 可能是超时或其他问题
      console.log('  ⚠️  cargo check 执行异常（可能是超时或环境问题）')
      warnings.push('cargo check 执行异常，请手动运行 cargo check 确认')
    }
  }
}

// ── 2. 根目录配置文件 ──────────────────────────────────────
console.log('\n📦  [2/10] 根目录配置文件')
check('package.json 存在', fileExists('package.json'))
check('package.json 含 tauri 命令', fileContains('package.json', '"tauri"'))
check('package.json 含 pnpm 包管理器', fileContains('package.json', '"pnpm"'))
check('index.html 存在', fileExists('index.html'))
check('vite.config.ts 存在', fileExists('vite.config.ts'))
check('tsconfig.json 存在', fileExists('tsconfig.json'))
check('tsconfig.node.json 存在', fileExists('tsconfig.node.json'))
check('README.md 存在', fileExists('README.md'))
check('LICENSE 存在', fileExists('LICENSE'))
check('tailwind.config.ts 不存在（v4 使用 Vite 插件）', !fileExists('tailwind.config.ts'))
check('postcss.config.js 不存在（v4 无需 PostCSS）', !fileExists('postcss.config.js'))
check('pnpm-lock.yaml 存在', fileExists('pnpm-lock.yaml'))

// ── 3. 前端源码核心文件 ────────────────────────────────────
console.log('\n⚛️   [3/10] 前端源码核心文件 (src/)')
const coreSrcFiles = [
  'src/main.tsx',
  'src/App.tsx',
  'src/vite-env.d.ts',
  'src/styles/globals.css',
  'src/styles/base.css',
  'src/styles/theme.css',
  'src/styles/tiptap.css',
  'src/styles/markdown.css',
  'src/types/index.ts',
  'src/lib/utils.ts',
  'src/lib/tauri-bridge.ts',
  'src/lib/toast.ts',
  'src/lib/image-utils.ts',
  'src/router/index.tsx',
  'src/plugins/index.ts',
  'src/plugins/types.ts',
  'src/plugins/PluginManager.ts',
]
for (const f of coreSrcFiles) check(f, fileExists(f))

check('plugins/examples/charCounter.ts', fileExists('src/plugins/examples/charCounter.ts'))

// ── 4. 状态管理 ────────────────────────────────────────────
console.log('\n🗄️   [4/10] 状态管理 (stores/)')
const storeFiles = [
  'src/stores/appStore.ts',
  'src/stores/appTypes.ts',
  'src/stores/uiAtoms.ts',
  'src/stores/aiStore.ts',
  'src/stores/booksStore.ts',
  'src/stores/pluginStore.ts',
  'src/stores/preferencesStore.ts',
]
for (const f of storeFiles) check(f, fileExists(f))

check(
  'appStore 为领域 store 出口 (booksStore/aiStore/preferencesStore)',
  fileContains('src/stores/appStore.ts', 'useBooksStore', 'useAiStore', 'usePreferencesStore')
)
check('uiAtoms 含 Jotai atom', fileContains('src/stores/uiAtoms.ts', "from 'jotai'"))
check('appTypes 含核心类型定义', fileContains('src/stores/appTypes.ts', 'Book', 'Chapter', 'Volume'))

// ── 5. 页面组件 ────────────────────────────────────────────
console.log('\n📄  [5/10] 页面组件 (pages/)')
check('LibraryPage.tsx', fileExists('src/pages/LibraryPage.tsx'))
check('EditorPage.tsx', fileExists('src/pages/EditorPage.tsx'))
check('SettingsPage.tsx (settings 路由入口)', fileExists('src/pages/SettingsPage.tsx'))
check('LibraryPage 含路由导入', fileContains('src/pages/LibraryPage.tsx', 'useNavigate'))
check('EditorPage 含 useParams', fileContains('src/pages/EditorPage.tsx', 'useParams'))

// ── 6. 功能组件 ────────────────────────────────────────────
console.log('\n🧩  [6/10] 功能组件 (components/)')

// App 初始化 & 通用
check('ErrorBoundary.tsx', fileExists('src/components/ErrorBoundary.tsx'))
check('AppInit.tsx', fileExists('src/components/app/AppInit.tsx'))
check('windowDetection.ts', fileExists('src/components/app/windowDetection.ts'))
check('ContextMenu.tsx', fileExists('src/components/common/ContextMenu.tsx'))
check('DebugPanel.tsx', fileExists('src/components/common/DebugPanel.tsx'))
check('ToastContainer.tsx', fileExists('src/components/common/ToastContainer.tsx'))

// 文库
check('BookCard.tsx', fileExists('src/components/library/BookCard.tsx'))
check('NewBookDialog.tsx', fileExists('src/components/library/NewBookDialog.tsx'))
check('EditBookDialog.tsx', fileExists('src/components/library/EditBookDialog.tsx'))
check('CoverPicker.tsx', fileExists('src/components/library/CoverPicker.tsx'))
check('TrashModal.tsx', fileExists('src/components/library/TrashModal.tsx'))

// 编辑器核心
check('RichTextEditor.tsx', fileExists('src/components/editor/RichTextEditor.tsx'))
check('EditorToolbar.tsx', fileExists('src/components/editor/EditorToolbar.tsx'))
check('ChapterSummaryHeader.tsx', fileExists('src/components/editor/ChapterSummaryHeader.tsx'))
check('SnapshotPanel.tsx', fileExists('src/components/editor/SnapshotPanel.tsx'))
check('ImageResizeNodeView.tsx', fileExists('src/components/editor/ImageResizeNodeView.tsx'))
check('ResizableImageExtension.ts', fileExists('src/components/editor/ResizableImageExtension.ts'))

// TipTap 依赖检查
check('RichTextEditor 含 TipTap useEditor', fileContains('src/components/editor/RichTextEditor.tsx', 'useEditor'))
check('RichTextEditor 含 StarterKit', fileContains('src/components/editor/RichTextEditor.tsx', 'StarterKit'))

// 布局
check('EditorLayout.tsx', fileExists('src/components/layout/EditorLayout.tsx'))
check('StatusBar.tsx', fileExists('src/components/layout/StatusBar.tsx'))

// 大纲 & 世界观
check('OutlinePanel.tsx', fileExists('src/components/outline/OutlinePanel.tsx'))
check('WorldbuildingPanel.tsx', fileExists('src/components/worldbuilding/WorldbuildingPanel.tsx'))
check('WorldCardEditor.tsx', fileExists('src/components/worldbuilding/WorldCardEditor.tsx'))

// AI 组件
check('AiSidePanel.tsx', fileExists('src/components/ai/AiSidePanel.tsx'))
check('AiToolboxPanel.tsx', fileExists('src/components/ai/AiToolboxPanel.tsx'))
check('MessageBubble.tsx', fileExists('src/components/ai/MessageBubble.tsx'))
check('RequestDetailModal.tsx', fileExists('src/components/ai/RequestDetailModal.tsx'))
check(
  'useAiChat 拆分：useAiChat.ts 复用 useAgentChatStream 流式监听',
  fileExists('src/components/ai/useAiChat.ts') &&
    fileContains('src/components/ai/hooks/useAgentChatStream.ts', 'agent-stream-chunk')
)

// 设置页
check('SettingsPage.tsx (详细设置)', fileExists('src/components/settings/SettingsPage.tsx'))
check('AiConfigSection.tsx', fileExists('src/components/settings/AiConfigSection.tsx'))
check('AiToolboxSection.tsx', fileExists('src/components/settings/AiToolboxSection.tsx'))
check('AppearanceSection.tsx', fileExists('src/components/settings/AppearanceSection.tsx'))
check('ChatConfigSection.tsx', fileExists('src/components/settings/ChatConfigSection.tsx'))
check('EditorConfigSection.tsx', fileExists('src/components/settings/EditorConfigSection.tsx'))
check('RagConfigSection.tsx', fileExists('src/components/settings/RagConfigSection.tsx'))
check('StorageSection.tsx', fileExists('src/components/settings/StorageSection.tsx'))
check('VersionSection.tsx', fileExists('src/components/settings/VersionSection.tsx'))
check('settings/constants.ts', fileExists('src/components/settings/constants.ts'))
check('settings/shared.tsx', fileExists('src/components/settings/shared.tsx'))

// Hooks
console.log('\n🪝  Hooks (hooks/)')
check('useAppVersion.ts', fileExists('src/hooks/useAppVersion.ts'))
check('useConsoleInterceptor.ts', fileExists('src/hooks/useConsoleInterceptor.ts'))
check('useResizeHandle.ts', fileExists('src/hooks/useResizeHandle.ts'))
check('useThemeFontInit.ts', fileExists('src/hooks/useThemeFontInit.ts'))

// ── 7. Rust 后端 ───────────────────────────────────────────
console.log('\n🦀  [7/10] Rust 后端 (src-tauri/)')

// 根文件
const rustCore = [
  'src-tauri/Cargo.toml',
  'src-tauri/tauri.conf.json',
  'src-tauri/build.rs',
  'src-tauri/src/main.rs',
  'src-tauri/src/lib.rs',
  'src-tauri/src/error.rs',
  'src-tauri/src/utils.rs',
]
for (const f of rustCore) check(f, fileExists(f))

// 数据库
check('db/mod.rs', fileExists('src-tauri/src/db/mod.rs'))
check('db/schema.rs', fileExists('src-tauri/src/db/schema.rs'))

// 模型 & 仓库层
check('models/mod.rs', fileExists('src-tauri/src/models/mod.rs'))
check('repository/mod.rs', fileExists('src-tauri/src/repository/mod.rs'))
const repos = ['book_repo', 'chapter_repo', 'volume_repo', 'snapshot_repo', 'world_card_repo', 'embedding_repo']
for (const r of repos) check(`repository/${r}.rs`, fileExists(`src-tauri/src/repository/${r}.rs`))

// 服务层
check('service/mod.rs', fileExists('src-tauri/src/service/mod.rs'))
const services = ['book_service', 'chapter_service', 'volume_service', 'snapshot_service', 'world_card_service', 'search_service']
for (const s of services) check(`service/${s}.rs`, fileExists(`src-tauri/src/service/${s}.rs`))

// IPC 命令
check('commands/mod.rs', fileExists('src-tauri/src/commands/mod.rs'))
const commands = ['book', 'chapter', 'volume', 'snapshot', 'world_card', 'image']
for (const c of commands) check(`commands/${c}.rs`, fileExists(`src-tauri/src/commands/${c}.rs`))

// AI 命令
check('commands/ai/mod.rs', fileExists('src-tauri/src/commands/ai/mod.rs'))
const aiCmds = ['chat', 'embedding', 'summarize', 'test']
for (const c of aiCmds) check(`commands/ai/${c}.rs`, fileExists(`src-tauri/src/commands/ai/${c}.rs`))

// IO 命令（backup 已于 v1.7.0 后拆分为目录模块：mod.rs + 6 个子模块文件）
check('commands/io/mod.rs', fileExists('src-tauri/src/commands/io/mod.rs'))
const ioCmds = ['crypto', 'export', 'import_txt']
for (const c of ioCmds) check(`commands/io/${c}.rs`, fileExists(`src-tauri/src/commands/io/${c}.rs`))
const backupMods = ['mod', 'types', 'export', 'import', 'import_log', 'reconcile', 'rollback']
for (const m of backupMods) check(`commands/io/backup/${m}.rs`, fileExists(`src-tauri/src/commands/io/backup/${m}.rs`))

// 窗口管理
check('commands/window/mod.rs', fileExists('src-tauri/src/commands/window/mod.rs'))
const windowCmds = ['debug', 'manager', 'validate']
for (const c of windowCmds) check(`commands/window/${c}.rs`, fileExists(`src-tauri/src/commands/window/${c}.rs`))

// 核心依赖检查
check('Cargo.toml 含 tauri v2', fileContains('src-tauri/Cargo.toml', 'tauri', 'protocol-asset'))
check('Cargo.toml 含 rusqlite (bundled)', fileContains('src-tauri/Cargo.toml', 'rusqlite'))
check('Cargo.toml 含 serde + serde_json', fileContains('src-tauri/Cargo.toml', 'serde'))
check('Cargo.toml 含 uuid', fileContains('src-tauri/Cargo.toml', 'uuid'))
check('Cargo.toml 含 chrono', fileContains('src-tauri/Cargo.toml', 'chrono'))
check('Cargo.toml 含 tokio (rt-multi-thread)', fileContains('src-tauri/Cargo.toml', 'tokio'))
check('Cargo.toml 含 reqwest', fileContains('src-tauri/Cargo.toml', 'reqwest'))
check('Cargo.toml 含 regex-lite', fileContains('src-tauri/Cargo.toml', 'regex-lite'))
check('Cargo.toml 含 aes-gcm (加密)', fileContains('src-tauri/Cargo.toml', 'aes-gcm'))

// lib.rs 注册关键命令
check('lib.rs 注册所有模块命令', fileContains(
  'src-tauri/src/lib.rs',
  'list_books', 'save_chapter', 'rag_search',
  'export_book', 'export_all_data', 'import_backup'
))

// 数据库结构检查
check('db/mod.rs 含 PRAGMA WAL', fileContains('src-tauri/src/db/mod.rs', 'WAL'))
// DDL 已按产品域拆分到 db/ddl/ 子目录；核心表结构由 ddl/core.rs 承载，
// 任务卡表由 ddl/taskcard.rs 承载（详见 src-tauri/src/db/ddl/mod.rs 的拆分说明）。
check('db/ddl/core.rs 含完整核心表结构 (books/chapters/volumes/snapshots/world_cards)',
  fileContains('src-tauri/src/db/ddl/core.rs',
    'CREATE TABLE IF NOT EXISTS books',
    'CREATE TABLE IF NOT EXISTS chapters',
    'CREATE TABLE IF NOT EXISTS snapshots'))
check('db/ddl/taskcard.rs 含任务卡核心表 (projects/tasks/tags/task_tags)',
  fileContains('src-tauri/src/db/ddl/taskcard.rs',
    'CREATE TABLE IF NOT EXISTS projects',
    'CREATE TABLE IF NOT EXISTS tasks',
    'CREATE TABLE IF NOT EXISTS task_tags'))
check('db/ddl/mod.rs 提供 apply_all_ddl 编排入口',
  fileContains('src-tauri/src/db/ddl/mod.rs', 'pub fn apply_all_ddl'))

// 架构验证
check('repository 层实现数据访问分离', fileContains('src-tauri/src/repository/book_repo.rs', 'rusqlite'))
check('service 层实现业务逻辑', fileContains('src-tauri/src/service/book_service.rs', 'book_repo'))
check('AI 模块含流式聊天 + RAG + 总结', fileContains('src-tauri/src/commands/ai/mod.rs', 'chat', 'embedding', 'summarize'))

// ── 8. 依赖与类型一致性 ─────────────────────────────────────
console.log('\n📐  [8/10] 依赖与类型一致性')
let pkgJson
try {
  pkgJson = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf-8'))
} catch { pkgJson = {} }
const deps = { ...pkgJson.dependencies, ...pkgJson.devDependencies }

// 核心框架
check('@tauri-apps/api (v2) 存在', !!deps['@tauri-apps/api'])
check('react + react-dom (v19) 存在', !!deps['react'] && !!deps['react-dom'])
check('typescript (>=6) 存在', !!deps['typescript'])
check('vite (v8) 存在', !!deps['vite'])

// Tauri 插件
check('@tauri-apps/plugin-dialog 存在', !!deps['@tauri-apps/plugin-dialog'])
check('@tauri-apps/plugin-fs 存在', !!deps['@tauri-apps/plugin-fs'])
check('@tauri-apps/plugin-http 存在', !!deps['@tauri-apps/plugin-http'])
check('@tauri-apps/plugin-shell 存在', !!deps['@tauri-apps/plugin-shell'])
check('@tauri-apps/plugin-updater 存在', !!deps['@tauri-apps/plugin-updater'])

// UI & 编辑器
check('@tiptap/react + starter-kit 存在', !!deps['@tiptap/react'] && !!deps['@tiptap/starter-kit'])
check('lucide-react 存在', !!deps['lucide-react'])
check('react-router-dom (v7) 存在', !!deps['react-router-dom'])
check('react-markdown + remark-gfm 存在', !!deps['react-markdown'] && !!deps['remark-gfm'])

// 状态管理
check('zustand (v5) 存在', !!deps['zustand'])
check('jotai 存在', !!deps['jotai'])

// 工具库
check('date-fns 存在', !!deps['date-fns'])
check('clsx + class-variance-authority 存在', !!deps['clsx'] && !!deps['class-variance-authority'])

// Tailwind CSS v4
check('tailwindcss (v4) + @tailwindcss/vite 存在', !!deps['tailwindcss'] && !!deps['@tailwindcss/vite'])

// 构建工具
check('@vitejs/plugin-react 存在', !!deps['@vitejs/plugin-react'])
check('esbuild 存在', !!deps['esbuild'])

// 前端 IPC 桥接一致性
check(
  'tauri-bridge 导出 bookApi/chapterApi/volumeApi/worldCardApi/aiApi',
  fileContains('src/lib/tauri-bridge.ts', 'bookApi', 'chapterApi', 'volumeApi', 'worldCardApi', 'aiApi')
)
check(
  '领域 store 含关键 action (booksStore/aiStore)',
  fileContains('src/stores/booksStore.ts', 'setBooks', 'setChapters', 'setVolumes', 'setCurrentChapterId') &&
  fileContains('src/stores/aiStore.ts', 'setAiConfig')
)

// ── 9. GitHub Actions & CI ─────────────────────────────────
console.log('\n🚀  [9/10] CI/CD (GitHub Actions)')
check('.github/workflows/release.yml 存在', fileExists('.github/workflows/release.yml'))
check('release.yml 含 Tauri 构建步骤', fileContains('.github/workflows/release.yml', 'tauri', 'build'))
const issueTemplates = [
  '.github/ISSUE_TEMPLATE/bug_report.yml',
  '.github/ISSUE_TEMPLATE/feature_request.yml',
  '.github/ISSUE_TEMPLATE/config.yml',
]
for (const t of issueTemplates) check(t, fileExists(t))

// ── 10. Agent 完整性检查（Rust 原生实现）─────────────────────
console.log('\n🦀  [10/10] Agent 引擎（Rust 原生）')

// Rust 原生 Agent 模块
const rustAgentFiles = [
  'src-tauri/src/commands/agent/mod.rs',
  'src-tauri/src/commands/agent/skills.rs',
  'src-tauri/src/commands/agent/prompts.rs',
  'src-tauri/src/commands/agent/tools.rs',
  'src-tauri/src/commands/agent/memory.rs',
  'src-tauri/src/commands/agent/engine.rs',
  'src-tauri/src/db/schema.rs',
]
for (const f of rustAgentFiles) check(`Rust Agent 模块 ${f}`, fileExists(f))

// 关键逻辑关键字检查
check('prompts.rs 含 4 个 Skill Prompt', fileContains('src-tauri/src/commands/agent/prompts.rs',
  'WRITING_PROMPT', 'ANALYSIS_PROMPT', 'RESEARCH_PROMPT', 'POLISH_PROMPT'))
check('engine.rs 含 SSE ReAct 循环', fileContains('src-tauri/src/commands/agent/engine.rs',
  'agent-stream-chunk', 'react_loop'))
check('tools.rs 含 6 个数据库工具', fileContains('src-tauri/src/commands/agent/tools.rs',
  'read_chapter', 'read_chapter_summary', 'read_chapter_chunk',
  'list_book_chapters', 'search_world_cards', 'get_book_context'))
check('memory.rs 含 memories 存取', fileContains('src-tauri/src/commands/agent/memory.rs',
  'extract_and_save', 'retrieve_memories', 'migrate_legacy_db'))
check('schema.rs 注册 memories 表', fileContains('src-tauri/src/db/schema.rs', 'memories'))

// 确认 Python Agent 目录已移除
const pythonStillPresent = fileExists('agent/main.py')
const pythonReferences = [
  ['manager.rs 移除', 'src-tauri/src/python/manager.rs'],
  ['bridge.rs 移除', 'src-tauri/src/python/bridge.rs'],
  ['client.rs 移除', 'src-tauri/src/python/client.rs'],
]
check('Python Agent 目录已移除 (agent/)', !pythonStillPresent)
for (const [desc, path] of pythonReferences) check(`${desc} (${path})`, !fileExists(path))
check('Cargo.toml 不再依赖 tiny_http', !fileContains('src-tauri/Cargo.toml', 'tiny_http'))

// 迁移收尾：无 Python 时代残留（防回归，防止旧脚本/命令/配置复活）
const noPythonOps = !fileContains('package.json', 'agent:setup') && !fileContains('package.json', 'agent:check')
const noPythonScripts = !fileExists('scripts/setup-agent.ts') && !fileExists('scripts/check-python-versions.ts')
const noLegacyCmds =
  !fileContains('src-tauri/src/lib.rs', 'start_agent') &&
  !fileContains('src-tauri/src/lib.rs', 'stop_agent') &&
  !fileContains('src-tauri/src/lib.rs', 'get_agent_status')
check('package.json 无 Python 运维命令 (agent:setup / agent:check)', noPythonOps)
check('Python 相关脚本已删除 (setup-agent / check-python-versions)', noPythonScripts)
check('pyrightconfig.json 已移除（曾指向 Python agent/）', !fileExists('pyrightconfig.json'))
check('lib.rs 无 Python 兼容命令 (start_agent / stop_agent / get_agent_status)', noLegacyCmds)
check('活文档无 uvicorn 残留 (README / ipc-api / FAQ)',
  !fileContains('README.md', 'uvicorn') &&
  !fileContains('docs/development/ipc-api.md', 'uvicorn') &&
  !fileContains('docs/FAQ.md', 'uvicorn'))

// ── 版本号一致性（10 个引用点，防漂移） ──────────────────────
// 单一真源：package.json 的 version。其余 9 处由 bump 脚本同步
// （.codebuddy/skills/version-release/scripts/bump_version.py），此处断言全部一致。
// 任一处遗漏 → 本项目检查失败，从机制上杜绝「发版后部分文档版本号停留在旧版」。
console.log('\n  ── 版本号一致性 ──')

function readJsonVersion(relPath) {
  try { return JSON.parse(readFileSync(join(ROOT, relPath), 'utf-8')).version ?? null } catch { return null }
}

function matchVersion(relPath, pattern) {
  try {
    const m = readFileSync(join(ROOT, relPath), 'utf-8').match(pattern)
    return m?.[1] ?? null
  } catch { return null }
}

const pkgVersion = readJsonVersion('package.json')
check('package.json 可读取版本号', !!pkgVersion)

if (pkgVersion) {
  const versionPoints = [
    ['src-tauri/tauri.conf.json', readJsonVersion('src-tauri/tauri.conf.json')],
    ['src-tauri/Cargo.toml', matchVersion('src-tauri/Cargo.toml', /^version\s*=\s*"([^"]+)"/m)],
    ['README.md（表格版本）', matchVersion('README.md', /\| 版本 \| (\d+\.\d+\.\d+) \|/)],
    ['README.md（当前版本行）', matchVersion('README.md', /\*\*当前版本：`(\d+\.\d+\.\d+)`\*\*/)],
    ['README.md（亮点行）', matchVersion('README.md', /> \*\*v(\d+\.\d+\.\d+) 亮点\*\*/)],
    ['docs/Home.md（当前版本）', matchVersion('docs/Home.md', /\| 当前版本 \| (\d+\.\d+\.\d+) \|/)],
    ['product/landing-page.html（Hero 徽章）', matchVersion('product/landing-page.html', /v(\d+\.\d+\.\d+) 已发布/)],
    ['product/landing-page.html（页脚）', matchVersion('product/landing-page.html', /TimeWrite<\/strong> &nbsp;·&nbsp; v(\d+\.\d+\.\d+)/)],
    ['.github/workflows/release.yml（默认版本）', matchVersion('.github/workflows/release.yml', /default:\s*'(\d+\.\d+\.\d+)'/)],
  ]

  for (const [label, v] of versionPoints) {
    const ok = v === pkgVersion
    check(`版本号一致 · ${label}：${v ?? '未匹配到版本'}${ok ? '' : ` ≠ ${pkgVersion}`}`, ok)
  }
}

// ── 窗口能力（capability）覆盖：防「权限缺失 → 功能静默失效」 ──
// 历史问题：debug/diary-book 未纳入任何 capability，调试控制台 listen 被拒；
// 主窗口缺 updater:default，导致「应用内更新」路径始终失败、静默降级到 GitHub 兜底。
console.log('\n  ── 窗口能力覆盖 ──')
check('capabilities/updater.json 存在（应用内更新权限）', fileExists('src-tauri/capabilities/updater.json'))
check('updater 能力授予 updater:default', fileContains('src-tauri/capabilities/updater.json', 'updater:default'))
check('updater 能力仅限主窗口（最小权限）', fileContains('src-tauri/capabilities/updater.json', '"main"'))
check('sub-windows 能力覆盖 debug / diary-book', fileContains('src-tauri/capabilities/sub-windows.json', '"debug"', '"diary-book"'))
check('lib.rs 注册 updater 插件', fileContains('src-tauri/src/lib.rs', 'tauri_plugin_updater'))

// ── IPC 注册一致性：#[tauri::command] 函数 ↔ invoke_handler! 注册项 ──
// 反向校验：扫描全部 .rs 源文件中标注 #[tauri::command] 的函数名，
// 与 lib.rs 中 invoke_handler! 实际注册的命令名双向比对。
// 任一方向不一致即失败：漏注册会导致前端 invoke 报 not found（运行时才发现）；
// 幽灵命令（注册了不存在的函数）通常源于重命名后遗漏，cargo 编译未必报错。
console.log('\n  ── IPC 注册一致性 ──')

function walkRsFiles(dir) {
  const out = []
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    if (e.isDirectory()) out.push(...walkRsFiles(p))
    else if (e.name.endsWith('.rs')) out.push(p)
  }
  return out
}

// 匹配 #[tauri::command] 标注的函数名（支持中间有 doc comment / pub async / pub fn）
// 形如：  #[tauri::command]\n pub async fn list_books(...)
const COMMAND_FN_RE = /#\[\s*tauri::command[^\]]*\]\s*(?:\/\/\/[^\n]*\n\s*)*(?:pub\s+)?(?:async\s+)?fn\s+(\w+)/g
const definedCommands = new Set()
for (const f of walkRsFiles(join(ROOT, 'src-tauri/src'))) {
  const txt = readFileSync(f, 'utf-8')
  let m
  while ((m = COMMAND_FN_RE.exec(txt))) definedCommands.add(m[1])
}

// 从 lib.rs 的 generate_handler![...] 块中提取注册的命令名（取路径最后一段）
const libRsContent = readFileSync(join(ROOT, 'src-tauri/src/lib.rs'), 'utf-8')
// 同时兼容 generate_handler![...] 与 invoke_handler!(...) 两种调用形式
const handlerBlockMatch = libRsContent.match(/(?:generate|invoke)_handler\s*!\s*[\(\[]([\s\S]*?)[\)\]]/)
const registeredCommands = new Set()
if (handlerBlockMatch) {
  const re = /commands(?:::[\w_]+)+::(\w+)/g
  let m
  while ((m = re.exec(handlerBlockMatch[1]))) registeredCommands.add(m[1])
}

check(`扫描到 #[tauri::command] 函数 (${definedCommands.size} 个)`, definedCommands.size > 0)
check(`lib.rs generate_handler! 注册命令 (${registeredCommands.size} 个)`, registeredCommands.size > 0)

const unregistered = [...definedCommands].filter(c => !registeredCommands.has(c)).sort()
check(`无漏注册命令（前端 invoke 会 not found）`, unregistered.length === 0)
if (unregistered.length > 0) {
  console.log(`     ↳ 漏注册 ${unregistered.length} 个：${unregistered.slice(0, 15).join(', ')}${unregistered.length > 15 ? ' ...' : ''}`)
}

const phantom = [...registeredCommands].filter(c => !definedCommands.has(c)).sort()
check(`无幽灵命令（注册了不存在的函数，多为重命名后遗漏）`, phantom.length === 0)
if (phantom.length > 0) {
  console.log(`     ↳ 幽灵 ${phantom.length} 个：${phantom.slice(0, 15).join(', ')}${phantom.length > 15 ? ' ...' : ''}`)
}

// ── IPC 命令名契约层：src/types/ipc-commands.ts ↔ Rust 源码 ──
// 单一真源：Rust 源码（#[tauri::command] 函数名）。
// check.mjs 自动生成并校验 ipc-commands.ts，漂移即失败。
// 前端可基于 IpcCommand 联合类型约束 invoke 调用，IDE 补全 + 编译期检查。
console.log('\n  ── IPC 命令名契约层 ──')
const ipcCommandsPath = join(ROOT, 'src/types/ipc-commands.ts')
const sortedCommands = [...definedCommands].sort()
const expectedContent = `// 自动生成,不要手动修改。由 scripts/check.mjs 从 src-tauri/src 中
// 所有 #[tauri::command] 标注的函数名提取。单一真源:Rust 源码。
// 漂移时 pnpm check 会失败;新增命令后重新运行 pnpm check 自动同步。

export type IpcCommand =
${sortedCommands.map(c => `  | '${c}'`).join('\n')}
`
if (!existsSync(ipcCommandsPath)) {
  writeFileSync(ipcCommandsPath, expectedContent, 'utf-8')
  check(`首次生成 src/types/ipc-commands.ts (${sortedCommands.length} 个命令)`, true)
  console.log(`     ↳ 已生成,后续运行将校验一致性`)
} else {
  const actual = readFileSync(ipcCommandsPath, 'utf-8')
  if (actual !== expectedContent) {
    // 自动同步:直接写回最新内容
    writeFileSync(ipcCommandsPath, expectedContent, 'utf-8')
    check(`src/types/ipc-commands.ts 与 Rust 源码一致(已自动同步)`, true)
    console.log(`     ↳ 检测到漂移,已自动同步 ${sortedCommands.length} 个命令`)
  } else {
    check(`src/types/ipc-commands.ts 与 Rust 源码一致 (${sortedCommands.length} 个命令)`, true)
  }
}

// ── 汇总 ────────────────────────────────────────────────────
console.log('\n' + '='.repeat(50))
const total = passed + failed
console.log(`\n📊  检测结果：${total} 项检查  ✅ ${passed} 通过  ❌ ${failed} 失败  ⚠️  ${warnings.length} 警告\n`)

if (errors.length > 0) {
  console.log('❌  失败项目：')
  errors.forEach(e => console.log(`   - ${e}`))
}
if (warnings.length > 0) {
  console.log('⚠️   警告项目：')
  warnings.forEach(w => console.log(`   - ${w}`))
}

if (failed === 0) {
  console.log('🎉  所有必需检查通过！项目基础代码完整。\n')
  console.log('📋  后续步骤：')
  console.log('   1. pnpm install')
  console.log('   2. pnpm tauri dev     （需先安装 Rust + Tauri CLI）')
  console.log('   3. 在设置中配置 DeepSeek / 智谱等云端模型 API Key')
  console.log()
  process.exit(0)
} else {
  console.log(`\n⚠️   存在 ${failed} 项失败，请检查上述文件。\n`)
  process.exit(1)
}
